#!/bin/bash

# Link to the binary
ln -sf '/opt/balenaEtcher/balena-etcher-electron' '/usr/bin/balena-etcher-electron'

# SUID chrome-sandbox for Electron 5+
# chmod 4755 '/opt/balenaEtcher/chrome-sandbox' || true

update-mime-database /usr/share/mime || true
update-desktop-database /usr/share/applications || true
